### ISSUE TITLE
Player scales incorrect

### ISSUE THREAD

**Issue by dickwolff** [Circularify/Seek-n-Play#10]
Due to YouTube their recent changes the player would not scale correctly according to its corner position.

**Steps to reproduce**
1. Go to YouTube
2. Click the first video in the feed
3. Watch a few seconds of the video
4. Click the YouTube-logo
5. Observe that the size of the video window is way smaller than the video itself

**Comment by dickwolff** [comment]
This issue is fixed in the master branch and will be available in next update

**Comment by rpaz-123** [comment]
This is again an issue in Seek n play 2.2.0.
Steps:
1 Open a video in youtube
2 Search another video in the search bar or click the youtube logo
3 The player resizes incorrectly in the corner

System:
Chrome version  52.0.2743.82 m
Windows 7

Extensions enabled:
Google Docs
