### ISSUE TITLE
New youtube look..

### ISSUE THREAD

**Issue by cococow123** [Circularify/Seek-n-Play#14]
Hello again!

Could you add support for the new youtube look ( _youtube.com/new_ )
This would be great!

Thanks,
Coco

**Comment by martijnlentink** [comment]
Hi Coco,

We are aware of the change and we are doing our best to add support for the new YT look.

-- Martijn

**Comment by dickwolff** [comment]
This issue is fixed in the latest Seek 'n Play release, v3.2.1.
