### ISSUE TITLE
Video only appears in corner

### ISSUE THREAD

**Issue by cococow123** [Circularify/Seek-n-Play#15]
Hello again!

I have found an issue.
After I watch a video and return to a webpage to search for more,  if I click fullscreen for the window in the corner, it only opens up to the size of the corner and not the whole page.

Ex: 
![image](https://cloud.githubusercontent.com/assets/16091192/26125438/252e08b8-3a50-11e7-84a0-1cfe84df969d.png)

**Comment by martijnlentink** [comment]
Thank you for your bug report. We looked into this issue and found the source of the problem, the fix is being uploaded to the Chrome Web Store as we speak. Further; I'd like to apologize for the late response to your report.
