### ISSUE TITLE
Seek 'n Play causes YouTube to freeze

### ISSUE THREAD

**Issue by dickwolff** [Circularify/Seek-n-Play#17]
As reported by multiple users, Seek 'n Play causes YouTube to freeze.

> Love this extension, been using it for a very long time. Suddenly youtube videos wont work, tried playing it in incognito and it worked. So tried disabling extensions one by one and disabling this made it work. Verified it by enabling and disabling again and checking. Please fix it! Thanks

> After the latest update, my chrome has been going unresponsive on youtube and I cannot watch any videos. Disabled for now, hopefully fixed soon.

**Comment by martijnlentink** [comment]
This issue was fixed in version 2.3.5
