### ISSUE TITLE
Option to close the floating player?

### ISSUE THREAD

**Issue by maple3142** [Circularify/Seek-n-Play#18]
How about add a button to temporary disable a floating window?
And re-enable it on next video.
![image](https://user-images.githubusercontent.com/9370547/42690460-d7be1652-86d6-11e8-8688-b43a2a2e8e02.png)

**Comment by martijnlentink** [comment]
Hi there maple3142,

Thank you for submitting your request. We will look into this and come back to you when/if we are planning to implement it. You aren't the first one that requests the ability to temporary disable the floating player.

-- Martijn

**Comment by martijnlentink** [comment]
Great news. We have implemented this request and plan to enable it next release. We are currently in the stage of testing.
