### ISSUE TITLE
Navigating with the player slider (while cornerized) doesn't work correctly

### ISSUE THREAD

**Issue by dickwolff** [Circularify/Seek-n-Play#4]
Seek 'n Play v2.0.1
Chrome 46.0.2490.86 m
Windows 10

While you are using the slider when seeking, the slider is ahead of where it plays.

**Steps to reproduce:**
1. Go to http://youtube.com
2. Search for 'Afrocircus'
3. Click the first video
4. Search for 'I like to move it' _[Seek 'n Play goes to Cornerize mode]_
5. Use the player slider to seek further in the video
6. Observe the red dot is ahead of where the actual video progressbar is.

**Comment by martijnlentink** [comment]
This issue is fixed in the master branch and will be available in next update
