### ISSUE TITLE
Clicking theater mode while in the corner messes with layout

### ISSUE THREAD

**Issue by martijnlentink** [Circularify/Seek-n-Play#6]
Affected OS: All

The video frame size does not scale correctly when theater mode is clicked while the player is in the corner.

**Steps to reproduce**:
1. Go to http://www.youtube.com
2. Search for 'Justin Bieber - Sorry'
3. Click the first video
4. Click the YouTube logo in the left upper corner
5. Click the 'Theater mode' button on the player
6. Return to the original video by clicking the expand button
7. Observe that the video scaled in proportion with the frame size

**Possible solution**
Hide the theater mode button altogether while the player is in the corner.

**Comment by dickwolff** [comment]
This bug is fixed and will be part of the next release.
